### ISSUE TITLE
extra bytes at beginning or within zipfile

### ISSUE THREAD

**Issue by ctatineni** [cloudfoundry/cli#1161]
Hello,

  I am trying to push an app on Mac , i am getting the below warning message.

warning [/tmp/staged/app/lib/jboss-logging-3.3.0.Final.jar]:  66802 extra bytes at beginning or within zipfile
  (attempting to process anyway)

this causes my service to fail, it works fine in windows, i am using cli V6.26.0.
any help would be appreciated.

**Comment by dkoper** [comment]
Hi @ctatineni 

Can you share with us the app (or a smallest subset of it, maybe with just that jar) for us to reproduce locally?

Cheers,
Dies Koper
CF CLI PM

**Comment by ctatineni** [comment]
i just created a simple spring boot hello world service and tried to deploy it to cloud foundry, during the deployment i see the warning messages. i tried to change the spring boot repackage layout and other configuration no luck, i am able to run it locally, i am suspecting it may have to do something with unzip or zip on CF cli.

**Comment by XenoPhex** [comment]
Not sure how you're building your `jar` (a full set of exact instructions on what you did would _strongly_ help debug this), but I just tried uploading the [test jar]( https://github.com/spring-guides/gs-rest-service/blob/master/run-on-pws.json#L17) provided in the `gs-rest-service` repo and it seemed to have worked fine:
```
$ cf push -p gs-rest-service-0.1.0.jar testarchive
Creating app testarchive in org anand-push-test / space test as admin...
OK

Creating route testarchive.bosh-lite.com...
OK

Binding testarchive.bosh-lite.com to testarchive...
OK

Uploading testarchive...
Uploading app files from: /tmp/unzipped-app151064708
Uploading 10.7M, 105 files
Done uploading               
OK

Starting app testarchive in org anand-push-test / space test as admin...
**TRIMMING LOGS**
Successfully created container
Downloading app package...
Downloaded app package (10.7M)
Staging...
malformed buildpack does not contain a /bin dir: 618aca78-8c90-4629-80b8-6f485a2128ac_9d037e024c4b7283441d199cb91ea0e1643d32cd0bae2ede4df70809d60e51d0
-----> Java Buildpack Version: v3.16 | https://github.com/cloudfoundry/java-buildpack.git#2110750
-----> Downloading Open Jdk JRE 1.8.0_131 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_131.tar.gz (1.7s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (2.6s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.3s)
       Memory Settings: -XX:MetaspaceSize=104857K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K
-----> Downloading Container Certificate Trust Store 2.1.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-certificate-trust-store/container-certificate-trust-store-2.1.0_RELEASE.jar (0.1s)
       Adding certificates to .java-buildpack/container_certificate_trust_store/truststore.jks (2.5s)
-----> Downloading Spring Auto Reconfiguration 1.11.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.11.0_RELEASE.jar (0.5s)
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (45M)
Uploaded droplet (56.1M)
Uploading complete
Destroying container

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App testarchive was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k.. -memoryWeights=heap:65,metaspace:10,native:15,stack:10 -memoryInitials=heap:100%,metaspace:100% -stackThreads=300 -totMemory=$MEMORY_LIMIT) && JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Djavax.net.ssl.trustStore=$PWD/.java-buildpack/container_certificate_trust_store/truststore.jks -Djavax.net.ssl.trustStorePassword=java-buildpack-trust-store-password" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`

Showing health and status for app testarchive in org anand-push-test / space test as admin...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: testarchive.bosh-lite.com
last uploaded: Thu Jun 15 17:14:41 UTC 2017
stack: cflinuxfs2
buildpack: container-certificate-trust-store=2.1.0_RELEASE java-buildpack=v3.16-https://github.com/cloudfoundry/java-buildpack.git#2110750 java-main open-jdk-like-jre=1.8.0_131 open-jdk-like-memory-calculator=2.0.2_RELEASE spring-auto-reconfiguration=1.11.0_RELEASE

     state     since                    cpu    memory       disk           details
#0   running   2017-06-15 10:16:16 AM   0.0%   304M of 1G   135.3M of 1G
```

**Comment by dkoper** [comment]
Closing. Without more help on how to reproduce the issue there is not much we can do.

**Comment by xiaozhu36** [comment]
HI @dkoper I also happened this issue and can you help me? 
The following is my case:
I want  to deploy [spring-music](https://github.com/cloudfoundry-samples/spring-music) by using  cf, but I happened this issue:
1. when I run command cf push firstly, it can deploy spring-music successfully;
2. when I run command cf push again, it throw many warnings, as following:
```
Staging app and tracing logs...
   Downloading binary_buildpack...
   Downloading staticfile_buildpack...
   Downloading java_buildpack...
   Downloading ruby_buildpack...
   Downloaded ruby_buildpack
   Downloading dotnet_core_buildpack...
   Downloaded staticfile_buildpack
   Downloading nodejs_buildpack...
   Downloaded java_buildpack
   Downloading go_buildpack...
   Downloaded binary_buildpack
   Downloading python_buildpack...
   Downloaded nodejs_buildpack
   Downloading php_buildpack...
   Downloaded dotnet_core_buildpack
   Downloading nginx_buildpack...
   Downloaded go_buildpack
   Downloading r_buildpack...
   Downloaded python_buildpack
   Downloaded r_buildpack
   Downloaded nginx_buildpack
   Downloaded php_buildpack
   Cell ae633763-c016-4a05-90c3-89494ac040e7 creating container for instance 700500a8-5455-4bba-b438-116f09231b82
   Cell ae633763-c016-4a05-90c3-89494ac040e7 successfully created container for instance 700500a8-5455-4bba-b438-116f09231b82
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded build artifacts cache (42.1M)
   Downloaded app package (62.4M)
   warning [/tmp/app/BOOT-INF/lib/spring-web-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/hibernate-core-5.2.16.Final.jar]:  6291456 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/jackson-databind-2.9.5.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-commons-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-mongodb-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-boot-autoconfigure-2.0.1.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/lettuce-core-5.0.3.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/aspectjweaver-1.8.13.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-core-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-context-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/h2-1.4.197.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-cloud-cloudfoundry-connector-2.0.1.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/hibernate-validator-6.0.9.Final.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/tomcat-embed-core-8.5.29.jar]:  2097152 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-redis-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/reactor-core-3.1.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/mongodb-driver-core-3.6.3.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-web-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/hibernate-core-5.2.16.Final.jar]:  6291456 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/jackson-databind-2.9.5.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-commons-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-mongodb-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-boot-autoconfigure-2.0.1.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/lettuce-core-5.0.3.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/aspectjweaver-1.8.13.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-core-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-context-5.0.5.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/h2-1.4.197.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-cloud-cloudfoundry-connector-2.0.1.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/hibernate-validator-6.0.9.Final.jar]:  1048576 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/tomcat-embed-core-8.5.29.jar]:  2097152 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/spring-data-redis-2.0.6.RELEASE.jar]:  1048576 extra bytes at beginning or within zipfile
```

**Comment by XenoPhex** [comment]
Can you please let us know the following:

1. Are you on the latest version of the CF CLI? (if not, please upgrade to the latest and try this push again)
1. What version of CF Deployment is your foundation running?

We believe we've fixed the extra-byte issues with JAR files years ago so updating to the latest CF CLI should have fixed the issue. Additionally, the errors that are coming up look to be an issue that occurs during the staging process, so it might not be related to the CF CLI.

**Comment by xiaozhu36** [comment]
HI. @XenoPhex Thanks for your feedback. Unfortunately, the issue still exist in the latest CF CLI version `cf version 6.51.0+2acd15650.2020-04-07` and my CF deployment version is `v12.31.0`. How to checking the staging process issue?

**Comment by XenoPhex** [comment]
@heyjcollins can you help with this?

**Comment by heyjcollins** [comment]
@XenoPhex and @xiaozhu36 - given this has occurred with very recent CF and CLI releases, reopening this issue so the team can take a look.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
