### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by tiga05** [cloudfoundry/cli#3194]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x]  I reviewed open and closed github issues that may be related to my problem.
- [x]  I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ]  I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x]  I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Like every year, the certificate has expired.
Also see:
https://github.com/cloudfoundry/cli/issues/2046
https://github.com/cloudfoundry/cli/issues/2571

**What happened**
While installing the CLI from debian repo this  issue occurs.
```
W: GPG error:
https://cf-cli-debian-repo.s3.amazonaws.com/
stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team
[cf-cli-eng@pivotal.io](mailto:cf-cli-eng@pivotal.io)
E: The repository '
https://cf-cli-debian-repo.s3.amazonaws.com/
stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Expected behavior**
- make a note in your calender and refresh the certificate BEFORE it has expired
- alternative: use a certificate which lasts longer but still set a reminder in your calender

**Exact Steps To Reproduce**
See above.

**Provide more context**
CF cli 8.X
Debian Version 12.6

**Comment by JKnudsen1337** [comment]
We have the same issue. We also had the same issue last year, and last year again :)
this time the --allow-unauthenticated unfortunately isn't helping us.

**Comment by Weltraumschaf** [comment]
BTW: Your [docs](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html) are outdated:

> wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
> echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

`apt-key` is deprecated since years!

I wonder why our devs use such a toy project maintained by few unprofessional hobbyists. I would prefer a more robust tool maintained by some professionals. Maybe with a backing company in the background. But what do I know...

**Comment by dbojaxhiu1** [comment]
We are also facing the same issue when trying to install cloud foundry from Azure DevOps Pipeline.

Since  task: CloudFoundryCLIInstall@ is no longer available in the Azure DevOps we are manually installing CF using below:

wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | tee /etc/apt/trusted.gpg.d/cf-cli.asc && \
echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list && \
....

We tried with --allow-unauthenticated -y and it seems to work, but this is not a solution we would go for.

Is there any expected time when this should get fixed?

Hopefully we will get a solution soon!

**Comment by tt-gsa** [comment]
Same issue here. This has broken our pipelines.

```bash
Get:4 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease [4,368 B]
Err:4 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease
  The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
Reading package lists... Done
W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
E: The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cf8-cli
```

**Comment by imshirk13** [comment]
Had the same issue, appreciate if you could update the issue as we have upcoming released and needs to deploy the app in azure devops. Thank you.

**Comment by ADPennington** [comment]
> Had the same issue, appreciate if you could update the issue as we have upcoming released and needs to deploy the app in azure devops. Thank you.

+ 1 (re: our release is delayed because of this)

**Comment by a-b** [comment]
https://github.com/cloudfoundry/cli/issues/3198#issuecomment-2344069403

**Comment by a-b** [comment]
This should be resolved by now. Please try 
```
curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire
gpg: key 172B5989FCD21EF8: "CF CLI Team <cf-cli-eng@pivotal.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pub   rsa4096 2018-09-13 [SC] [expires: 2025-09-11]
sub   rsa4096 2018-09-13 [E] [expires: 2025-09-11]
```
and let us know if CND propagated on your end.

**Comment by tt-gsa** [comment]
> This should be resolved by now. Please try
> 
> ```
> curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire
> gpg: key 172B5989FCD21EF8: "CF CLI Team <cf-cli-eng@pivotal.io>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> pub   rsa4096 2018-09-13 [SC] [expires: 2025-09-11]
> sub   rsa4096 2018-09-13 [E] [expires: 2025-09-11]
> ```
> 
> and let us know if CDN propagated on your end.

I've tried in a clean Debian container and still having the issue:
```bash
root@99d91c9731a6:/# date && curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire
Wed Sep 11 17:22:19 UTC 2024
gpg: key 172B5989FCD21EF8: "CF CLI Team <cf-cli-eng@pivotal.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pub   rsa4096 2018-09-13 [SC] [expired: 2024-09-10]
uid           [ expired] CF CLI Team <cf-cli-eng@pivotal.io>
```

**Comment by tt-gsa** [comment]
Confirming that it's now working for us.

**Comment by imshirk13** [comment]
Hello, can this be reopen? its happening again. :(

**Comment by tt-gsa** [comment]
> curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire

Confirmed for us as well, in a clean Debian container:

```bash
root@905487b04837:/# date && curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --import - ; gpg --list-keys | grep expire
Thu Sep 12 17:18:11 UTC 2024
gpg: key 172B5989FCD21EF8: "CF CLI Team <cf-cli-eng@pivotal.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pub   rsa4096 2018-09-13 [SC] [expired: 2024-09-10]
uid           [ expired] CF CLI Team <cf-cli-eng@pivotal.io>
```

**Comment by greensomes** [comment]
I'm encountering an issue too:
```
Err:8 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 172B5989FCD21EF8
Reading package lists... Done
W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 172B5989FCD21EF8
E: The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
