### ISSUE TITLE
6.11.0+ error fetching logs from ER 1.3

### ISSUE THREAD

**Issue by wgu** [cloudfoundry/cli#423]
Noticed the release log that from 6.11.0 on doppler will be added to the cli config file. Seems it will now be the default URL when fetching app logs? 

sgu-home:cf-chatroom sgu$ cf target

API endpoint:   https://api.system.10.10.33.11.xip.io (API version: 2.13.0)
User:           admin
Org:            system
Space:          dev
sgu-home:cf-chatroom sgu$ cf -v
cf version 6.11.0-bba7fcf-2015-04-14T16:45:03+00:00
sgu-home:cf-chatroom sgu$ cf logs riakcs-sgu
FAILED
Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.system.10.10.33.11.xip.io:443)

The trace log indicated the same connection error. 

6.10.0 works just fine.

**Comment by goehmen** [comment]
Yes.  This is a bug that we addressed in v6.11.1.  Can you upgrade your CLI and confirm that the issue is resolved?  thanks

**Comment by wgu** [comment]
Sorry, just about to reply that 6.11.1 does not work either. Replaced the binary, logout, clean the cli config file and then login. Still the same.

sgu-home:cf-chatroom sgu$ cf logs chatter
FAILED
Error dialing traffic controller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.system.10.10.33.11.xip.io:443).
sgu-home:cf-chatroom sgu$ cf -v
cf version 6.11.1-4ef66f6-2015-04-20T21:15:38+00:00

**Comment by goehmen** [comment]
hmmm....ok.  thanks.

Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by simonleung8** [comment]
Seems like the doppler endpoint is not available in the env.
Do you also get the same message with `cf push` or `cf app <app_name>`?

**Comment by wgu** [comment]
Yes, I do.

**Comment by nebhale** [comment]
Guys, this is also demonstrable against PWS at the moment.  Should we be rolling the Homebrew Tap back to the v6.10 line?

```
$: cf push
Using manifest file [REDACTED]/web-servlet-2-application/manifest.yml

Using stack cflinuxfs2...
OK
Updating app web-servlet-2-application in org [REDACTED] / space [REDACTED] as [REDACTED]...
OK

Uploading web-servlet-2-application...
Uploading app files from: [REDACTED]/web-servlet-2-application-1.0.0.BUILD-SNAPSHOT.war
Uploading 429.3K, 29 files
Done uploading               
OK

Stopping app web-servlet-2-application in org [REDACTED] / space [REDACTED] as [REDACTED]...
OK

Warning: error tailing logs
Loggregator endpoint missing from config file
Starting app web-servlet-2-application in org [REDACTED] / space [REDACTED] as [REDACTED]...
```

```
$: cf logs web-servlet-2-application --recent
Connected, dumping recent logs for app web-servlet-2-application in org [REDACTED] / space [REDACTED] as [REDACTED]...

FAILED
Error dialing traffic controller server: parse : empty url.
Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller endpoint is ).
```

**Comment by simonleung8** [comment]
@nebhale : Does logging out and back in solve your problem? It seems to be looking for the new doppler endpoint in the config and the field will be populated during `cf api` or `cf login`

**Comment by nebhale** [comment]
@simonleung8 That does seem to solve the problem, but as far as usability goes it's horrible.  That logging in again fixes the problem is effectively undiscoverable by normal users.

**Comment by goehmen** [comment]
We're going to provide a fix in 6.11.2 which we are working on now.

Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by goehmen** [comment]
The CLI team worked through this with the LAMB team.  We have a solution that we will be implementing in the next release.  Basically, we need to be able to interrogate the CC API and address either the Doppler or the Loggregator endpoint based on interrogation.
