### ISSUE TITLE
"cf api" fails if the 1st nameserver fails to resolve the endpoint

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry/cli#763]
Condition:
Several name servers are defined in /etc/resolv.conf:
nameserver "internal"
nameserver "public"
Then, the "api endpoint" is accessible from nameserver "public", but not from nameserver "internal".

In this situation, I can 
1 . ping "api endpoint" successfully,  
2.  curl "api endpoint"/v2/info successfully
3. nslookup "api endpoint" successfully
nslookup "api endpoint" 
;; Got recursion not available from "internal", trying next server
Server:        "public"
Address:    "public"#53
Non-authoritative answer:
Name:    "api endpoint"
Address: "ip address of api endpoint"
4. But failed with "cf api" cmd:
  [exec] Setting api endpoint to https://"api endpoint" ...
  [exec] FAILED
  [exec] Error performing request: Get https://"api endpoint" /v2/info: dial tcp: lookup "api endpoint"  on "internal":53: no such host

It looks like "cf api" cmd only check the 1st nameserver, and fails to do recursive lookup as nslookup, curl, ping and etc system cmd.

**Comment by dkoper** [comment]
Hi @cdlliuy,

If you change the Go resolver, does it make a difference?
`GODEBUG=netdns=cgo cf api https://api endpoint`

**Comment by cdlliuy** [comment]
hi, @dkoper , it works with GODEBUG=netdns=cgo cf api https://api endpoint, but when I do "cf login", I must "GODEBUG=netdns=cgo cf login -a https://api.xxx" , and the further request must be works with "GODEBUG=netdns=cgo" as well, i.e. "GODEBUG=netdns=cgo cf apps". 

I think this is a workaround, right?

**Comment by dkoper** [comment]
Hi @cdlliuy,
Thanks for getting back to me so quickly.
The CLI is implemented in Golang, which defaults to a DNS resolver that doesn't seem to cater for your use case. Setting the environment variable makes it use a non-default DNS resolver that does cater for your use case.
The CLI team will need to investigate the impact of changing the CLI to use the other resolver by default.

In the meantime, you can set GODEBUG=netdns=cgo as a global environment variable in your shell so cf (and other programs developed in Golang that likely weren't able to resolve external addresses either) will work.

Regards,
Dies Koper
CF CLI PM

**Comment by cdlliuy** [comment]
Got it. Thanks Dies

**Comment by rahulkj** [comment]
Hi @dkoper

Oh yes, the issue we're facing is the same. But without setting GODEBUG=netdns=cgo for v6.15.0 it works fine. So v6.16.x doesn't work with this flag.

**Comment by robdimsdale** [comment]
Possibly related, we noticed that cf v6.16 does not handle a misconfigured `/etc/resolv.conf` on linux well. Because of the [hard-coded 5 second timeout](https://github.com/cloudfoundry/cli/blob/aa1c389162d53caec986a96ef370d8bd7a4ac142/cf/net/gateway.go#L451) when configuring `net.Dial`, if the DNS resolution takes longer than 5 seconds, the CLI will exit with error. I created https://www.pivotaltracker.com/story/show/115252237 to address this.

We saw the above behavior on a bosh-deployed 64-bit linux VM (for cf-smoke-tests) that had a bad entry in `/etc/resolv.conf` but could not reproduce this on OSX. Possibly related to the fact that the linux 64-bit CLI is dynamically-linked and all other binaries are statically-linked.

We have also had similar reports from the CF community in the last week or so (see https://github.com/cloudfoundry/cf-release/issues/923).

**Comment by cbguder** [comment]
@cdlliuy we were unable to reproduce this on Ubuntu Trusty or Wily, using CLI 6.16.1.

Can you tell us more about your system?

You can see our attempt to reproduce below:

```
$ cat /etc/resolv.conf 
nameserver 127.0.0.1
nameserver 10.0.2.3

$ nslookup api.run.pivotal.io 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find api.run.pivotal.io: REFUSED

$ nslookup api.run.pivotal.io
;; Got recursion not available from 127.0.0.1, trying next server
Server:		10.0.2.3
Address:	10.0.2.3#53

Non-authoritative answer:
Name:	api.run.pivotal.io
Address: 54.236.99.215
Name:	api.run.pivotal.io
Address: 54.175.152.201

$ cf api api.run.pivotal.io
Setting api endpoint to api.run.pivotal.io...
OK

                   
API endpoint:   https://api.run.pivotal.io (API version: 2.51.0)   
Not logged in. Use 'cf login' to log in.
```

**Comment by cdlliuy** [comment]
@cbguder, the problem happens on 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00, and I don't have permission to change the cf version of the target env.   I contact the admin and check whether v6.16.1 works

**Comment by SimyungYang** [comment]
$ cf --version
cf version 6.16.1+924508c-2016-02-26

I installed cf-cli through brew installer, and the version was the 6.16.1
with the version, I was continually gettting the error message as follows.


```
$ cf api https://api.run.pivotal.io

Error performing request: Get https://login.run.pivotal.io/login: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```

even with `GODEBUG=netdns=go` and `GODEBUG=netdns=cgo` option, it failed.
 

But when i reinstall cf-cli version 6.15.0, it works.
I guess there is some issue on the latest version.

**Comment by vvraskin** [comment]
We face the same issue when trying to execute the following command:

`$ cf install-plugin Diego-Enabler -r CF-Community -f
Looking up 'Diego-Enabler' from repository 'CF-Community'
FAILED
Error getting plugin metadata from repo: Error requesting from 'CF-Community' - Get http://plugins.cloudfoundry.org/list: dial tcp: lookup plugins.cloudfoundry.org on first_dns_server:53: n
o such host`

Have tried with CF cli `6.16.1` and `6.15.0` on `Ubuntu 14.04.4,  3.13.0-63-generic`.
It worked only with `GODEBUG=netdns=cgo` enabled on both versions and failed with `GODEBUG=netdns=go`.

**Comment by dkoper** [comment]
@cdlliuy @vvraskin 

We have released cf CLI 6.18.0 with changes that may affect its behaviour in circumstances such as the ones you have described. Would you mind trying it out and report back how it works without the environment variables, and with?

Cheers,
Dies Koper
CF CLI PM

**Comment by vvraskin** [comment]
@dkoper 
Hello, 

I've checked the latest version of cf CLI (6.18.1+a1103f0-2016-05-24) and I still see similar problems. 

Command:

`CF_TRACE=true ./cf api api.fabric.ng.mydomain.net`

Output:

`Setting api endpoint to api.fabric.ng.mydomain.net...

REQUEST: [2016-06-01T02:08:44-05:00]
GET /v2/info HTTP/1.1
Host: api.fabric.ng.mydomain.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.18.1+a1103f0 / linux


fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7fc851a0db2c]

runtime stack:
runtime.throw(0xf62a20, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 810 [syscall, locked to thread]:
runtime.cgocall(0xafdea0, 0xc820036bd8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820036b78 sp=0xc820036b48
net._C2func_getaddrinfo(0x7fc8440008c0, 0x0, 0xc82042e2d0, 0xc8200740c0, 0x0, 0x0, 0x0)
	??:0 +0x55 fp=0xc820036bd8 sp=0xc820036b78
net.cgoLookupIPCNAME(0xc8204fe1e0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101f800)
	/usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820036d50 sp=0xc820036bd8
net.cgoLookupIP(0xc8204fe1e0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x409f45)
	/usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820036da8 sp=0xc820036d50
net.lookupIP(0xc8204fe1e0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820036e18 sp=0xc820036da8
net.glob.func16(0x101f828, 0xc8204fe1e0, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820036e58 sp=0xc820036e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820036ed8 sp=0xc820036e58
internal/singleflight.(*Group).doCall(0x15ec1c0, 0xc82050a140, 0xc8204fe1e0, 0x19, 0xc8204fe260)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820036f88 sp=0xc820036ed8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820036f90 sp=0xc820036f88
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc8201fc000, 0xc8203f0000, 0x0, 0xc820430900, 0x5, 0xc8204fe1e0, 0x1d, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8201fc000, 0xc8203f0000, 0xc8201fc000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc8203f0000, 0x7fc852d84598, 0xc8201fc000, 0x0, 0x0, 0x0, 0xc82042e210, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc820430960, 0xc8203f0000, 0x0, 0x0, 0x0, 0xc820228e74, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc820430960, 0xc8203f0000, 0x101fa50, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc820430960, 0xc8203f0000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
github.com/cloudfoundry/cli/cf/net.Gateway.doRequest(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:432 +0x144
github.com/cloudfoundry/cli/cf/net.Gateway.doRequestAndHandlerError(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:404 +0x5e
github.com/cloudfoundry/cli/cf/net.Gateway.doRequestHandlingAuth(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:375 +0x190
github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:254 +0x8d
github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:274 +0x9a
github.com/cloudfoundry/cli/cf/net.Gateway.GetResource(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:102 +0x160
github.com/cloudfoundry/cli/cf/api.RemoteInfoRepository.getCCAPIInfo(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/api/endpoints.go:51 +0x12c
github.com/cloudfoundry/cli/cf/api.RemoteInfoRepository.GetCCInfo(0x7fc852d954a8, 0xc8200e4fd0, 0x101ea38, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7fc852d95068, 0xc8204324b0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/api/endpoints.go:33 +0x20e
github.com/cloudfoundry/cli/cf/api.(*RemoteInfoRepository).GetCCInfo(0xc8201f1320, 0x7ffc587265f0, 0x19, 0x40000000, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:31 +0xf1
github.com/cloudfoundry/cli/cf/configuration/coreconfig.APIConfigRefresher.Refresh(0x7fc852d956b8, 0xc8201f1320, 0x7fc852d95170, 0xc8204324b0, 0x7ffc587265f0, 0x19, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/configuration/coreconfig/api_config_refresher.go:24 +0x88
github.com/cloudfoundry/cli/cf/commands.Api.setAPIEndpoint(0x7fc852d94ed0, 0xc820434040, 0x7fc852d956b8, 0xc8201f1320, 0x7fc852d95170, 0xc8204324b0, 0x7ffc587265f0, 0x19, 0x0, 0xe54758, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/commands/api.go:97 +0x307
github.com/cloudfoundry/cli/cf/commands.Api.Execute(0x7fc852d94ed0, 0xc820434040, 0x7fc852d956b8, 0xc8201f1320, 0x7fc852d95170, 0xc8204324b0, 0x7fc852d98b88, 0xc82041e340)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/commands/api.go:76 +0xc09
github.com/cloudfoundry/cli/cf/commands.(*Api).Execute(0xc8204302a0, 0x7fc852d98b88, 0xc82041e340)
	<autogenerated>:4 +0xaa
main.main()
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:118 +0x1782

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 809 [select]:
net.lookupIPDeadline(0xc8204fe1e0, 0x19, 0xecee08101, 0x73cb5dc, 0x15ed2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xe59db0, 0x3, 0xc8204fe1e0, 0x1d, 0xecee08101, 0x73cb5dc, 0x15ed2a0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xe55650, 0x4, 0xe59db0, 0x3, 0xc8204fe1e0, 0x1d, 0xecee08101, 0x73cb5dc, 0x15ed2a0, 0x0, ...)
	/usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc8201162d0, 0xe59db0, 0x3, 0xc8204fe1e0, 0x1d, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0xe59db0, 0x3, 0xc8204fe1e0, 0x1d, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:458 +0x6e
net/http.(*Transport).dial(0xc8201fc000, 0xe59db0, 0x3, 0xc8204fe1e0, 0x1d, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:659 +0x96
net/http.(*Transport).dialConn(0xc8201fc000, 0x0, 0xc820430900, 0x5, 0xc8204fe1e0, 0x1d, 0xc82005fc80, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8201fc000, 0x0, 0xc820430900, 0x5, 0xc8204fe1e0, 0x1d, 0xc8203c64e0)
	/usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:708 +0x262`

Command:

`CF_TRACE=true GODEBUG=netdns=go ./cf api.fabric.ng.mydomain.net`

Output:

`root@boshcli:~# CF_TRACE=true GODEBUG=netdns=go ./cf api api.fabric.ng.mydomain.net
Setting api endpoint to api.fabric.ng.mydomain.net...

REQUEST: [2016-06-01T02:03:54-05:00]
GET /v2/info HTTP/1.1
Host: api.fabric.ng.mydomain.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.18.1+a1103f0 / linux



REQUEST: [2016-06-01T02:03:54-05:00]
GET /v2/info HTTP/1.1
Host: api.fabric.ng.mydomain.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.18.1+a1103f0 / linux


FAILED
Error performing request: Get http://api.fabric.ng.mydomain.net/v2/info: dial tcp: lookup api.fabric.ng.mydomain.net on 192.155.213.160:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.`



I have following DNS configuration in /etc/resolv.conf:
`
nameserver 127.0.0.1 # Consul DNS
nameserver 192.155.213.160 # powerDNS 
nameserver 10.0.80.12 # Softlayer DNS
`
The address I'm trying to resolve (http://api.fabric.ng.mydomain.net) is located on the Softlayer DNS.  nslookup and ping can resolve it, but dig is failing.
However, when I try to comment the powerDNS entry in /etc/resolv.conf, dig is working, but cf api is showing the error.
So I think that the problem is that cf client still cannot iterate over all DNS entries in /etc/resolv.conf.

**Comment by umairriaz82** [comment]
Hello

i'm using the latest cf version 6.19.0+b29b4e0-2016-06-08 and keep getting the same message.  if i tether laptop to my phone, i can login, push applications, but soon as i am connected to my home wireless... i get the following errors when i try to do "cf login, cf push , etc"

 auth request failed: Error performing request: Post https://login.run.pivotal.io/oauth/token: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

**Comment by dkoper** [comment]
@cdlliuy, @umairriaz82, @SimyungYang, @rahulkj 
Possibly the issue is that the cf CLI has a (hardcoded) 5 sec timeout for resolving the domain name and connecting to the IP address. So if /etc/resolv.conf is configured to switch to the secondary DNS server after 5 seconds (its documented default timeout value), the CLI will already have given up.
In cf CLI 6.20.0 we have experimentally replaced the hardcoded value with an environment variable `CF_DIAL_TIMEOUT` to allow you to override the 5 sec timeout. Please let us know how that works out for you.

@vvraskin If you can reproduce the panic with cf CLI 6.20.0, please submit a new issue and we'll take a look.

Cheers,
Dies Koper
CF CLI PM

**Comment by giner** [comment]
There is a feeling that cf cli makes a DNS request for every connection to API and does not reuse already resolved name. This feeling comes from cf being slow if when dns is slow.

**Comment by dkoper** [comment]
@giner I believe the idea was that the connection would be reused for subsequent API calls, so there would be no need to cache resolved addresses (a process which leave to golang, which doesn't seem to come with a cache itself).
As part of another investigation we recently found out that we're not reusing connections. I was about to create a story for that. Feel free to create a new GitHub issue for that to make it easier for you to track.

Regards,
Dies Koper
CF CLI PM

**Comment by cdlliuy** [comment]
@dkoper,  with the cf cli "cf version 6.19.0+b29b4e0-2016-06-08"  , the workaround "export GODEBUG=netdns=cgo" can't work anymore . Here is the cmd & response I got 

>>:~$ cf -v
cf version 6.19.0+b29b4e0-2016-06-08
>>:~$ export GODEBUG=netdns=cgo
>>:~$ cf api http://api.<domain>
Setting api endpoint to http://api.<domain>...
FAILED
Error performing request: Get http://api.<domain>/v2/info: dial tcp: lookup api.<domain> on 10.117.176.18:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

========
In the meanwhile, the ping & nslookup both work:
>>:~$ ping api.<domain>
PING <domain> (158.85.156.18) 56(84) bytes of data.
64 bytes from 12.9c.559e.ip4.static.sl-reverse.com (158.85.156.18): icmp_seq=1 ttl=185 time=226 ms
64 bytes from 12.9c.559e.ip4.static.sl-reverse.com (158.85.156.18): icmp_seq=2 ttl=185 time=226 ms
64 bytes from 12.9c.559e.ip4.static.sl-reverse.com (158.85.156.18): icmp_seq=3 ttl=185 time=226 ms
^C
--- <domain> ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 226.650/226.766/226.860/0.087 ms

>>:~$ nslookup api.<domain>
;; Got recursion not available from 10.117.176.18, trying next server
Server:		10.0.80.11
Address:	10.0.80.11#53

Non-authoritative answer:
api.<domain>	canonical name = <domain>.
Name:	<domain>
Address: 158.85.156.18

=========
On another similar env, the "cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00" cli worked with workaround  "export GODEBUG=netdns=cgo" .

At this time point, I hope to get the workaround works again

**Comment by dkoper** [comment]
@cdlliuy 
Can you try increasing the dial timeout by setting environment variable `CF_DIAL_TIMEOUT` (in seconds, defaults to 5) in your shell when running the `cf` command and report back?

**Comment by cdlliuy** [comment]
@dkoper, here you go.  You can see I set the timeout to 20, and using "date" to dump the time.  But the cf cmd failed almost at one, and didn't wait for 20 seconds at all .
>>:~$ export GODEBUG=netdns=cgo
>>:~$ cf api https://api.<domain>
Setting api endpoint to https://api.<domain>...
FAILED
Error performing request: Get https://api.<domain>/v2/info: dial tcp: lookup api.<domain> on 10.117.176.18:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
>>:~$ export CF_DIAL_TIMEOUT=20
>>:~$ date
Sat Jul 30 03:37:29 CDT 2016
>>:~$ cf api https://api.<domain>
Setting api endpoint to https://api.<domain>...
FAILED
Error performing request: Get https://api.<domain>/v2/info: dial tcp: lookup api.<domain> on 10.117.176.18:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
>>:~$ date
Sat Jul 30 03:37:35 CDT 2016

**Comment by cdlliuy** [comment]
@dkoper, see my latest post for the CF_DIAL_TIMEOUT on v6.19 version. Is that worth to try on v6.20 version?

**Comment by dkoper** [comment]
@cdlliuy yes, the variable was introduced in v6.20.0. Sorry, I should have mentioned that!

**Comment by cdlliuy** [comment]
@dkoper , the CF_DIAL_TIMEOUT didn't work even with cf v6.21.  The same behaviour as v6.19, no effect at all.  Also, it didn't wait for 20 seconds when setting to CF_DIAL_TIMEOUT=20

:/tmp$ cf -v
cf version 6.21.0+dff2cf8-2016-07-27
:/tmp$ date
Wed Aug 10 04:06:16 CDT 2016
:/tmp$ export CF_DIAL_TIMEOUT=20
:/tmp$ GODEBUG=netdns=cgo cf api https://api.<domain>
Setting api endpoint to https://api.<domain> ...
FAILED
Error performing request: Get https://api.<domain>/v2/info: dial tcp: lookup api.ng.bluemix.net on 168.1.59.87:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

:/tmp$ date
Wed Aug 10 04:06:21 CDT 2016

**Comment by cdlliuy** [comment]
@dkoper , is there any progress on this issue?

**Comment by amenzhinsky** [comment]
I'm having the same problem, dns responds with:
```
;; ANSWER SECTION:
<cut>.com. 21599 IN	CNAME	<cut>.elb.amazonaws.com.
```

My cli version:
```
cf version 6.21.1+6fd3c9f-2016-08-10
```

But if I build it by myself with `bin/build` script, it works well

**Comment by amenzhinsky** [comment]
Some more information:

Turned out official binary is already built with go's dns resolver and there's no way to switch it to cgo with environment variable.
```
go package net: built with netgo build tag; using Go's DNS resolver
FAILED
```

My binary (golang 1.7)
```
go package net: dynamic selection of DNS resolver
OK

go package net: using cgo DNS resolver
OK

go package net: GODEBUG setting forcing use of Go's resolver
FAILED
```

**Comment by amenzhinsky** [comment]
Probably you should remove the `netgo` build flag?

**Comment by cdlliuy** [comment]
In my case, the cli didn't work whatever GODEBUG=netdns=cgo set or unset.  Is  there anyone to take care this issue?

**Comment by dkoper** [comment]
Hi @cdlliuy 

We're concerned we're building the CLI with Go's DNS resolver to allow static building so that the binary works on more Linux distributions (in particular, also on minimal distributions like Alpine) and therefore the ability to make it switch to the cgo resolver dynamically is disabled.
I've asked the team to take another look.

**Comment by nickwei84** [comment]
@cdlliuy @dkoper 
We've rebuilt the CLI with go 1.7.1 which has fixed a [bug](https://github.com/golang/go/issues/16865) related to DNS retry logic. Can you please see if you still run into this issue with the latest [edge binaries](https://github.com/cloudfoundry/cli/wiki/Edge-Binaries). In the meantime we will try to reproduce this issue on our end.

**Comment by cdlliuy** [comment]
@nickwei84 , do you mean the latest CLI binary 6.21.1 in the download page??

**Comment by dkoper** [comment]
@cdlliuy No, the *edge* binaries, also available from the links in the last section of https://github.com/cloudfoundry/cli#downloads.

**Comment by nickwei84** [comment]
@cdlliuy 
If you are still running into a DNS issue with the latest edge binary, can you please provide us with one of the following:
1. provide us access to your environment so we can directly debug your issue instead of reproducing it in our environment which may differ
2. provide us with the following additional information:
- contents of your `/etc/resolv.conf` file
- output from running `nslookup "your-domain"`
- output from running `nslookup "your-domain" dns-server-from-/etc/resolv.conf` for each domain name server in your `/etc/resolv.conf` file
- output from running `dig "your-domain"`
- output from running `ping "your-domain"`
- output from running both `tcpdump -ni eth0 -v port 53&` (this will run in the background) and then `cf api "your-domain"`

Thanks!

**Comment by cdlliuy** [comment]
The edge build works in my environment! thanks a lot!

**Comment by dkoper** [comment]
Thanks again for your cooperation and patience in resolving this issue.
We have published the release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by pmaitra** [comment]
I had downloaded the latest version:
C:\Users\pradipta>cf --version
cf version 6.22.1+6b7af9c-2016-09-24

However, I am still stuck with the same problem:
C:\Users\pradipta>cf_edge api https://api.springcloudeureka.com
Setting api endpoint to https://api.springcloudeureka.com...
FAILED
Error performing request: Get https://api.springcloudeureka.com/v2/info: dial tc
p 92.242.132.27:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_pr
oxy environment variable is correctly set. Else, check your network connection.

**Comment by dkoper** [comment]
@pmaitra, please submit a new issue as with our tracking system it is difficult to track issues that have been marked resolved.
Please include full details. In your post above you show the version of `cf` but you run the api command on `cf_edge`? What did you set `CF_DIAL_TIMEOUT` to? What does `curl -vvv` to the same API endpoint return? Please include that in the issue report.

**Comment by opeadeyomoye** [comment]
Hello all,

Just wanted to mention; I've had this issue with the DNS timeouts for quite a while now, but the **CF_DIAL_TIMEOUT** environment variable worked for me. I set it to a value of 20 and I'm now able to 
run `cf l -a https://<api endpoint> ...` and login successfully.

@dkoper mentioned on https://www.pivotaltracker.com/n/projects/892938/stories/113792769 that nobody had come back to report success, so here's one.
